spring:
  application:
    name: companies
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: debuggeandoideas
    password: udemy123
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5